# Generated by Django 3.0.6 on 2020-07-28 17:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200318_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_profile.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[300, 300], upload_to='profile_pics'),
        ),
    ]
