# Generated by Django 3.1.5 on 2021-12-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł przepisu')),
                ('recipe_type', models.CharField(choices=[('wypiek', 'wypiek'), ('deser', 'deser'), ('zupa', 'zupa'), ('inne', 'inne')], default='inne', max_length=100, verbose_name='Typ przepisu')),
                ('certified', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False, verbose_name='Zgadzam się z przedstawionymi mi warunkami i opublikuj mój przepis')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_recipe.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[300, 300], upload_to='recipe_pics', verbose_name='Wprowadź Obraz')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='Krutka deskrypcja przepisu')),
                ('method', models.TextField(blank=True, max_length=10000, verbose_name='Wprowadź instrukcję sukcesywnego wykonania produktu')),
                ('license', models.TextField(default='MIT License\n\nCopyright (c) [year] [fullname]\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.', max_length=10000, verbose_name='Utwórz licencję')),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=100, verbose_name='Wybierz narodowość przepisu')),
                ('date_posted_old', models.DateTimeField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edited', models.DateTimeField(blank=True, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Wydawca')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Tytuł kategorii')),
                ('ingredients', models.TextField(db_index=True, max_length=500, verbose_name='Wprowadź listę składników do następującej kategorii')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
