# Generated by Django 3.0.4 on 2020-05-06 20:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='recipe',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=100, verbose_name='Wybierz narodowość przepisu'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Zgadzam się z przectawionymi warunkami i opublikuj mój przepis'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_posted_old',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
