# Generated by Django 3.0.4 on 2020-03-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200322_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='recipe',
        ),
    ]
