# Generated by Django 3.0.6 on 2020-07-28 17:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200715_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_recipe.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[300, 300], upload_to='recipe_pics', verbose_name='Wprowadź Obraz'),
        ),
    ]
