# Generated by Django 3.0.4 on 2020-04-27 18:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Opublikuj przepis'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=100, verbose_name='Wybierz narodowość przepisu'),
        ),
    ]
