# Generated by Django 3.0.4 on 2020-04-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200427_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_posted_old',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
