# Generated by Django 3.0.4 on 2020-04-28 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200427_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
