# Generated by Django 3.0.4 on 2020-04-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200428_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
