# Generated by Django 3.0.4 on 2020-03-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200323_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tytuł kategorii'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ingredients',
            field=models.TextField(db_index=True, max_length=240, verbose_name='Wprowadź listę składników do następującej kategorii'),
        ),
    ]
