# Generated by Django 3.0.4 on 2020-04-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200403_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='Krutka deskrypcja przepisu'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Wprowadź instrukcję sukcesywnego wykonania produktu'),
        ),
    ]
