# Generated by Django 3.0.4 on 2020-04-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20200408_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_recipe.svg', upload_to='recipe_pics', verbose_name='Wprowadź Obraz'),
        ),
    ]
