# Generated by Django 3.0.4 on 2020-04-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20200415_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_recipe.jpg', upload_to='recipe_pics', verbose_name='Wprowadź Obraz'),
        ),
    ]
